# Generated by Django 4.2.5 on 2024-04-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_option_question_poll_option_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
            preserve_default=False,
        ),
    ]
